### ISSUE TITLE
Image Exception : #3 :: Attempted to divide images/ROIs of different sizes

### ISSUE THREAD

**Issue by tragus1** [poldracklab/fmriprep#979]
Standard error:
Image Exception : #3 :: Attempted to divide images/ROIs of different sizes
terminate called after throwing an instance of 'RBD_COMMON::BaseException'
Aborted (core dumped)
Return code: 134

fMRIPrep: Please report errors to https://github.com/poldracklab/fmriprep/issues

Any ideas what went wrong?

**Comment by chrisfilo** [comment]
Did the HTML reports get created? If so could you share them?

**Comment by tragus1** [comment]
Unfortunately no HTML reports were created.

**Comment by chrisfilo** [comment]
Ok thanks. Does the validator pass on the input data? https://github.com/INCF/bids-validator

If it passes - could you share the problematic data.

**Comment by tragus1** [comment]
Hi,

this is a dataset with 29 participants. It passes the BIDS validator without an error.
Here you can find the problematic data set:  https://1drv.ms/f/s!Aggqz7_2LyPfht44YBym0MYCkUVDzA

thanks,
Boris

**Comment by tragus1** [comment]
I rerun the pipeline and now I got a different error:

Standard error:

    Using antsBrainExtraction with the following arguments:
      image dimension         = 3
      anatomical image        = /root/src/fmriprep/work/fmriprep_wf/single_subject_HCP002S6007w_wf/anat_preproc_wf/anat_template_wf/t1_conform/mapflow/_t1_conform0/sub-HCP002S6007w_T1w_ras.nii.gz
      extraction template     = /niworkflows_data/ants_oasis_template_ras/T_template0.nii.gz
      extraction reg. mask    = /niworkflows_data/ants_oasis_template_ras/T_template0_BrainCerebellumRegistrationMask.nii.gz
      extraction prior        = /root/src/fmriprep/work/fmriprep_wf/single_subject_HCP002S6007w_wf/anat_preproc_wf/skullstrip_ants_wf/t1_skull_strip/T_template0_BrainCerebellumProbabilityMask.nii.gz
      output prefix           = highres001_
      output image suffix     = nii.gz

    N4 parameters (pre brain extraction):
      convergence             = [50x50x50x50,0.0000001]
      shrink factor           = 4
      B-spline parameters     = [200]

    Atropos parameters (extraction):
       convergence            = [3,0.0]
       likelihood             = Gaussian
       initialization         = kmeans[3]
       mrf                    = [0.1,1x1x1]
       use clock random seed  = 1

/usr/lib/ants/antsBrainExtraction.sh: line 117:  7840 Segmentation fault      (core dumped) $cmd
Return code: 1

similar to what I got in a different post and thought to be related with memory issues. But this time I used the --mem_mb flag.

Thanks

**Comment by chrisfilo** [comment]
Are you running via Docker for Mac or Windows? If so please make sure to
increase the amount of host memory exposed by Docker in Docker preferences
from the default 2gb to at least 8gb.

Best,
Chris

**Comment by tragus1** [comment]
Iḿ running it on ubuntu 16.04. As fas as I know there is no memory limit set as default.

**Comment by chrisfilo** [comment]
Correct. You might still be running into memory issues. How much total and
free memory are you seeing on your system?

Best,
Chris

**Comment by tragus1** [comment]
The system comes with 32 GB RAM. Available I have around 30 GB.

**Comment by effigies** [comment]
Can you share your full command line?

**Comment by tragus1** [comment]
python '/home/demenzbild/Schreibtisch/fmriprep-docker-1.0.6.post2/fmriprep_docker.py' --fs-license-file /home/demenzbild/Schreibtisch/license.txt /home/demenzbild/Schreibtisch/TAUREST/BIDS_TAUREST /home/demenzbild/Schreibtisch/TAUREST/BIDS_TAUREST_out participant --mem_mb 30

**Comment by tragus1** [comment]
I can only use the cmd: python '/home/demenzbild/Schreibtisch/fmriprep-docker-1.0.6.post2/fmriprep_docker.py' 
fmriprep-docker -v isn´t working for some strange reason.

**Comment by effigies** [comment]
How did you install `fmriprep-docker`? Your pip installation directory may not be in your PATH.

**Comment by chrisfilo** [comment]
Actually to speed the debugging process up - @tragus1 could you try uploading a test dataset to http://OpenNeuro.org and running fmriprep on it? I just deployed version 1.0.7

**Comment by tragus1** [comment]
I can do that later. For the moment Iḿ rerunning fmriprep and now everything looks good. Mayabe the incorrect memory definition was actually the problem.

**Comment by tragus1** [comment]
I still get similar error messages. I uploaded a test dataset with 3 participants to OpenNeuro.

**Comment by tragus1** [comment]
Standard error:

    Using antsBrainExtraction with the following arguments:
      image dimension         = 3
      anatomical image        = /root/src/fmriprep/work/fmriprep_wf/single_subject_HCP002S6009m_wf/anat_preproc_wf/anat_template_wf/t1_conform/mapflow/_t1_conform0/sub-HCP002S6009m_T1w_ras.nii.gz
      extraction template     = /niworkflows_data/ants_oasis_template_ras/T_template0.nii.gz
      extraction reg. mask    = /niworkflows_data/ants_oasis_template_ras/T_template0_BrainCerebellumRegistrationMask.nii.gz
      extraction prior        = /root/src/fmriprep/work/fmriprep_wf/single_subject_HCP002S6009m_wf/anat_preproc_wf/skullstrip_ants_wf/t1_skull_strip/T_template0_BrainCerebellumProbabilityMask.nii.gz
      output prefix           = highres001_
      output image suffix     = nii.gz

    N4 parameters (pre brain extraction):
      convergence             = [50x50x50x50,0.0000001]
      shrink factor           = 4
      B-spline parameters     = [200]

    Atropos parameters (extraction):
       convergence            = [3,0.0]
       likelihood             = Gaussian
       initialization         = kmeans[3]
       mrf                    = [0.1,1x1x1]
       use clock random seed  = 1

/usr/lib/ants/antsBrainExtraction.sh: line 117: 31200 Segmentation fault      (core dumped) $cmd
Return code: 1

**Comment by tragus1** [comment]
It's finished on OpenNeuro without any error. I have no idea what's wrong with my system. Do you have any suggestions?

**Comment by chrisfilo** [comment]
Things I can think off (in order of likelihood):
1. FMRIPREP is overcommiting memory (trying to run too many things at the same time). To test this theory try to run a single participant using `--participant_label` (choose a participant that previously yielded erro locally, but run without issue on OpenNeuro).
2. Your RAM is corrupted. You can test your memory using https://www.memtest86.com/
3. There could've been a mysterious bug in 1.0.6 (that you have locally) concerning ANTs we are not aware which was accidentally fixed in 1.0.7 (installed on openneuro). You can test this by running 1.0.7 on your data.

**Comment by tragus1** [comment]
My memory is ok. The problem is overcoming memory. When I run only a single subject or 4 subjects at once it finishes without errors. Is there a way to deal with that issue? It's not really comfortable to process the study in several parts. 

Thanks

**Comment by chrisfilo** [comment]
There is nothing conceptually wrong in doing one subject at a time, but you
can artificially limit parallelization with --n_threads parameter.
Alternatively you can specify less memory than your system have using
--mem_mb  to avoid overcommiting.

Best,
Chris

**Comment by tragus1** [comment]
Even with limited threads or memory the core dumped. For some strange reason it's not running on my Linux system. It worked well on my old mac notebook with the same data but fewer participants. I need the computing power of the Linux system to run the whole dataset.

**Comment by oesteban** [comment]
Have you run the participant `sub-HCP002S6009m` on your mac? What is the command line you are using this time?

**Comment by tragus1** [comment]
I think I did't run this sub on my mac. I'm using:
fmriprep-docker --fs-license-file /home/demenzbild/Schreibtisch/license.txt /home/demenzbild/Schreibtisch/TAUREST/BIDS_TAUREST /home/demenzbild/Schreibtisch/TAUREST/BIDS_TAUREST_OUT2 participant --nthreads 8

or 

fmriprep-docker --fs-license-file /home/demenzbild/Schreibtisch/license.txt /home/demenzbild/Schreibtisch/TAUREST/BIDS_TAUREST /home/demenzbild/Schreibtisch/TAUREST/BIDS_TAUREST_OUT2 participant --mem_mb 16000

Also Iḿ running fmriprep v1.0.7 now.

**Comment by oesteban** [comment]
I'm thinking that this could be a problem with that specific subject (an empty image, wrong headers, ...). Can you rule that hypothesis out?

If everything looks good at once, I'd try running that particular subject on your mac.

**Comment by tragus1** [comment]
This hypothesis cannot be right because this subject was processed without error on OpenNeuro.

**Comment by chrisfilo** [comment]
I would try lowering the `--nthreads` to 1 and if this solves the segmentation faults issue try with higher numbers.

**Comment by tragus1** [comment]
Even with --nthreads 1 I get the core dumped error on an different participant: 


ERROR: command exited with nonzero status 139
Command: /usr/lib/ants/antsRegistration -d 3 -u 1 -w [0.025,0.975] -o highres001_BrainExtractionPrior -r highres001_BrainExtractionInitialAffine.mat -z 1 --float 1 --verbose 1 -x [/niworkflows_data/ants_oasis_template_ras/T_template0_BrainCerebellumRegistrationMask.nii.gz] -m MI[/niworkflows_data/ants_oasis_template_ras/T_template0.nii.gz,highres001_N4Corrected0.nii.gz,1,32,Regular,0.25] -c [1000x500x250x100,1e-8,10] -t Rigid[0.1] -f 8x4x2x1 -s 4x2x1x0 -m MI[/niworkflows_data/ants_oasis_template_ras/T_template0.nii.gz,highres001_N4Corrected0.nii.gz,1,32,Regular,0.25] -c [1000x500x250x100,1e-8,10] -t Affine[0.1] -f 8x4x2x1 -s 4x2x1x0 -m CC[/niworkflows_data/ants_oasis_template_ras/T_template0.nii.gz,highres001_N4Corrected0.nii.gz,0.5,4] -m CC[highres001_BrainExtractionTemplateLaplacian.nii.gz,highres001_BrainExtractionLaplacian.nii.gz,0.5,4] -c [50x10x0,1e-9,15] -t SyN[0.1,3,0] -f 4x2x1 -s 2x1x0

Standard error:

    Using antsBrainExtraction with the following arguments:
      image dimension         = 3
      anatomical image        = /root/src/fmriprep/work/fmriprep_wf/single_subject_HCP941S4365m_wf/anat_preproc_wf/anat_template_wf/t1_conform/mapflow/_t1_conform0/sub-HCP941S4365m_T1w_ras.nii.gz
      extraction template     = /niworkflows_data/ants_oasis_template_ras/T_template0.nii.gz
      extraction reg. mask    = /niworkflows_data/ants_oasis_template_ras/T_template0_BrainCerebellumRegistrationMask.nii.gz
      extraction prior        = /root/src/fmriprep/work/fmriprep_wf/single_subject_HCP941S4365m_wf/anat_preproc_wf/skullstrip_ants_wf/t1_skull_strip/T_template0_BrainCerebellumProbabilityMask.nii.gz
      output prefix           = highres001_
      output image suffix     = nii.gz

    N4 parameters (pre brain extraction):
      convergence             = [50x50x50x50,0.0000001]
      shrink factor           = 4
      B-spline parameters     = [200]

    Atropos parameters (extraction):
       convergence            = [3,0.0]
       likelihood             = Gaussian
       initialization         = kmeans[3]
       mrf                    = [0.1,1x1x1]
       use clock random seed  = 1

/usr/lib/ants/antsBrainExtraction.sh: line 117: 12490 Segmentation fault      (core dumped) $cmd
Return code 1

Its a pity that fmriprep is not running on my system.

**Comment by oesteban** [comment]
Please reopen if this is not actually fixed.
